apiVersion: apps/v2
kind: Deployment
metadata:
  name: media-deployment
  labels:
    app: media
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
      - name: job-portal
        image: mdinesh28/job-portal
        ports:
        - containerPort: 8080
      - name: candycrush
        image: mdinesh28/candycrush
        ports:
        - containerPort: 8081
      - name: quora
        image: mdinesh28/quora
        ports:
        - containerPort: 8082
      - name: imdb
        image: mdinesh28/imdb
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  - protocol: TCP
    port: 81
    targetPort: 8081
  - protocol: TCP
    port: 82
    targetPort: 8082
  - protocol: TCP
    port: 83
    targetPort: 8083
  type: LoadBalancer
